site_name: Fleting Docs
site_url: https://alexyucra.github.io/Fleting/
use_directory_urls: true
theme:
  name: material
  language: en
  features:
    - navigation.tabs        
    - navigation.sections   
    - navigation.instant    
    - content.code.copy     
plugins:
  - search
  - i18n:
      languages:
        - locale: en
          name: English
          default: true
          build: true
        - locale: pt
          name: Português
          build: true
        - locale: es
          name: Español
          build: true

nav:
  - Home: index.md
  - Português:
      - Início: pt/index.md
      - Arquitetura: pt/arquitetura.md
      - Checklist: pt/checklist.md
      - CLI: pt/cli.md
      - Ambiente: pt/enviroment.md
  - Español:
      - Inicio: es/index.md
      - Arquitectura: es/arquitectura.md
      - Checklist: es/checklist.md
      - CLI: es/cli.md
      - Entorno: es/enviroment.md
  - Contribuir: CONTRIBUTING.md

